"""Bundle assets/py/*.py into assets/pyfiles.js so index.html works from file:// (no fetch needed)."""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent


def main():
    files = {p.name: p.read_text(encoding="utf-8") for p in sorted((ROOT / "assets" / "py").glob("*.py"))}
    out = ROOT / "assets" / "pyfiles.js"
    out.write_text(
        "// Generated by tools/build_pyfiles.py from assets/py/*.py - do not edit by hand.\n"
        "window.PYFILES = " + json.dumps(files, ensure_ascii=False, indent=1) + ";\n",
        encoding="utf-8",
    )
    print(f"wrote {out} ({', '.join(files)})")


if __name__ == "__main__":
    main()
